#!/usr/bin/env node

var program = require('commander');

var argv = process.argv;

program
  .version('0.1.0')
  .usage('<type> <name> [options]')
  .option('-p, --path [path]', 'path to directory to which recipe will be copied')
  .option('-r, --revert', 'should scaffolt revert changes done by previous scaffolding?')
  .option('-g, --generators [path]', 'path to directory which contains generators specifications [./generators]')
  .option('-h, --helpers [path]', 'path to helper definition file which contains Handlebars helpers [./helpers.js]')
  .option('-l, --list', 'list availables generators')
  .option('-d, --doc [type]', 'display generator documentation');

program.on('--help', function() {
  console.log('  Examples:');
  console.log('');
  console.log('    scaffolt view user');
  console.log('    scaffolt model cart --revert');
  console.log('    scaffolt controller header --path controllers/regions/header.coffee');
  console.log('    scaffolt view product --helpers customHelpers.js');
  console.log('    scaffolt --list');
  console.log('    scaffolt collection --doc');
  console.log('');
});

program.parse(process.argv);

var args = program.args;
var count = args.length;
var first = args[0];
var type, name;


var scaffolt = require('./');

if (program.list) {
  scaffolt.list({
    generatorsPath: program.generators
  });
}
else if (program.doc) {
  if (count < 1) program.help();

  if ([program.doc].indexOf(first) === -1) {
    type = first;
  } else {
    type = args[count - 1];
  }

  scaffolt.help( type, {
    generatorsPath: program.generators
  });
}
else
{
  if (count < 2) program.help();

  if ([program.path, program.revert, program.generators, program.helpers].indexOf(first) === -1) {
    type = first;
    name = args[1];
  } else {
    type = args[count - 2];
    name = args[count - 1];
  }

  if (!type || !name) program.help();

  scaffolt(type, name, {
    parentPath: program.path,
    generatorsPath: program.generators,
    helpersPath: program.helpers,
    revert: program.revert,
  });
}
